{{/*
SPDX-FileCopyrightText: (c) 2025 Rowan Gillson <devops@the.bald.engineer>
SPDX-License-Identifier: MIT
*/}}

{{- $refreshPeriod := "168h" }}

{{/* Define cross platform externals first */}}

{{/* WSL specific externals */}}

{{- if and .target.wsl (or .secrets.apikeys .secrets.sshkeys .secrets.storagekeys) }}
".local/bin/age":
  type: archive-file
  url: "https://github.com/FiloSottile/age/releases/download/v{{ .tools.binaries.age }}/age-v{{ .tools.binaries.age }}-{{ .chezmoi.os }}-{{ .chezmoi.arch }}.tar.gz"
  executable: true
  path: age/age
{{- end }}

{{/* Darwin specific externals */}}
