".local/share/tmux/plugins/tpm":
  type: archive
  url: https://github.com/tmux-plugins/tpm/archive/master.zip
  exact: true
  stripComponents: 1
  refreshPeriod: 168h

".local/share/nvim/site/autoload/plug.vim":
  type: file
  url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  refreshPeriod: 168h
