{{/*
SPDX-FileCopyrightText: (c) 2025 Rowan Gillson <devops@the.bald.engineer>
SPDX-License-Identifier: MIT
*/}}

{{- $refreshPeriod := "168h" }}

"aura-theme-dark.kdl":
  type: file
  url: "https://raw.githubusercontent.com/arrrgi/aura-theme/refs/heads/feat/zellij/packages/zellij/aura-theme-dark.kdl"
{{/* refreshPeriod: {{ $refreshPeriod }} */}}
  path: "./aura-theme-dark.kdl"
