{{/*
SPDX-FileCopyrightText: (c) 2025 Rowan Gillson <devops@the.bald.engineer>
SPDX-License-Identifier: MIT
*/}}

{{- $refreshPeriod := "168h" }}

"colors.yaml":
  type: file
  url: "https://raw.githubusercontent.com/arrrgi/aura-theme/refs/heads/feat/lsd/packages/lsd/dark-colors.yaml"
{{/* refreshPeriod: {{ $refreshPeriod }} */}}
  path: "./colors.yaml"
