{{/*
SPDX-FileCopyrightText: (c) 2025 Rowan Gillson <devops@the.bald.engineer>
SPDX-License-Identifier: MIT
*/}}

{{- $refreshPeriod := "168h" }}

"aura-theme-dark.yml":
  type: file
  url: "https://raw.githubusercontent.com/arrrgi/aura-theme/refs/heads/feat/vivid/packages/vivid/aura-theme-dark.yml"
  refreshPeriod: {{ $refreshPeriod }}
  path: "./aura-theme-dark.yml"
