{{/*
SPDX-FileCopyrightText: (c) 2023 Rowan Gillson <devops@the.bald.engineer>
SPDX-License-Identifier: MIT
*/}}

{{- $refreshPeriod := "168h" }}

"themes":
  type: archive
  url: "https://github.com/rose-pine/zellij/archive/refs/heads/main.zip"
  exact: true
  stripComponents: 2
  refreshPeriod: {{ $refreshPeriod }}
