{{/*
SPDX-FileCopyrightText: (c) 2025 Rowan Gillson <devops@the.bald.engineer>
SPDX-License-Identifier: MIT
*/}}

{{- $refreshPeriod := "168h" }}

"rose-pine.lua":
  type: archive-file
  url: "https://github.com/neapsix/wezterm/archive/refs/heads/main.zip"
  path: plugin/init.lua
  stripComponents: 1
  refreshPeriod: {{ $refreshPeriod }}
