name: Publish docs to gh-pages

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "docs/**"
      - ".github/mkdocs.yml"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Python runtime
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.9

      - name: Set the date environment variable for cache keying
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - name: Setup build cache
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install dependencies
        run: pip install mkdocs-material pillow cairosvg

      - name: Publish documentation
        run: mkdocs gh-deploy --config-file ./.github/mkdocs.yml --force
