name: Update copyright year(s) in license file

on:
  schedule:
    - cron: "0 12 1 1 *" # 12:00 PM on January 1

permissions:
  contents: write
  pull-requests: write

jobs:
  update-license-year:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: FantasticFiasco/action-update-license-year@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
